### ISSUE TITLE
Add Swift Package Manager 4 manifest file

### ISSUE THREAD

**Issue by rootscript** [trsathya/Cryptex#2]
Would be great to be able to import Cryptex using SwiftPM

**Comment by trsathya** [comment]
@rootscript Feel free to send a pull request.

**Comment by rootscript** [comment]
@trsathya  - thanks for the quick reply.  Unfortunately, I am not skilled enough to make the changes to upgrade the manifest file.  But I  can point you to docs, if that makes things easier: <https://swift.org/blog/swift-package-manager-manifest-api-redesign/>
&
<https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md>

If I could fix it myself I would, but I have less than 24 hours experience with swift ( just a hobbyist swift scripter )
