### ISSUE TITLE
Binance Exchange example, documentation.

### ISSUE THREAD

**Issue by rootscript** [trsathya/Cryptex#5]
@trsathya Hello again.  This Cryptex package installs fine using Swift Package Manager 4.

I would like to `import Cryptex` but would be grateful for an example of how to use the Cryptex package with the Binance exchange.

I'm guessing that I will need to generate an `Api Key` and `Api Secret`, but I'm unsure of how to use your module.

**Comment by trsathya** [comment]
Yes, Will add **Usage** section in README.md in next release. 

In the meanwhile, create a temporary currencyStore like https://gist.github.com/trsathya/1ee672de3933b1b4b56891c3baf4212c.

Thanks, instantiate Binance api client as shown below.

```
let key = "<Your binance account api key>"
        let secret = "<Your binance account api secret>"
        let session = URLSession.shared
        let userPreference = UserPreference(fiat: .USDT, crypto: .Bitcoin, ignoredFiats: [], currencyStore: CurrencyStore.shared)
        let binanceAPIClient = Binance.Service(key:key, secret: secret, session: session, userPreference: userPreference)
```

**Comment by trsathya** [comment]
@rootscript Checkout v0.0.4 https://github.com/trsathya/Cryptex/releases/tag/0.0.4
